### ISSUE TITLE
Import data from "Where Is It?" software

### ISSUE THREAD

**Issue by lfigueirabr** [PJDude/librer#1]
Greetings! For the users of "Where Is It?" software, it would be essential to have an import feature in librer where it can read the data contained in its .CTF catalog files and make it available to search.
For example, WinCatalog has this import feature: https://www.wincatalog.com/whereisit-export.html

**Comment by PJDude** [comment]
Hi. It definitely looks doable (if we mean importing from an .xml report file and not a .ctf one). I used "Where is it" myself many years ago, in the era of CDs and DVDs. I'll think about that.

**Comment by PJDude** [comment]
[librer v1.0092.584](https://github.com/PJDude/librer/releases/tag/v1.0092.584)
stay tuned.

**Comment by PJDude** [comment]
https://github.com/PJDude/librer/releases/tag/v1.0096.566
